### ISSUE TITLE
My Orders - orders listing table

### ISSUE THREAD

**Issue by kajalshah** [galenp/PROPERTYCOMPASS.ISSUES#6] opened 2015-04-29 06:41 UTC
Please see attached

Thanks,
![orderstable-29april2015](https://cloud.githubusercontent.com/assets/6513000/7385758/ce87e68a-ee68-11e4-9f2a-fa0a7c6e66df.png)

**Comment by galenp** [comment] 2015-04-29 06:58
The Pay button behavior uses the default stored payment method if it exists.
The drop down gives a list of all stored payment methods.
If no stored payment method exists it takes the user to the new credit card payment interface.

I agree if there is no stored payment method the arrow can be removed.

As for changing the name from Orders to Transactions i would like to discuss this further.

To me (and as per current design) an  Order represents:
- a billable customer
- a collection of 1 or more order line items
- the amount outstanding
- tax considerations

This aggregation of information is called an 'Order'.
To me a 'Transaction' represents an attempt at triggering a 'Payment' that can either succeed or fail.

Due to this I do not thing we rename to Transactions.
I personally think Orders is the correct name but am open to discuss this further.

I am certainly open to input in addressing how the menu/navigation should be set up to access 'My Orders'

I encourage you to look at http://203.59.72.103:20004/ which is the template we are using for the application and note how the user can click their name to get a personalised menu. I think 'My Orders' could perhaps live in here.

**Comment by kajalshah** [comment] 2015-04-29 07:15
Hi,
If I think as a user who is new to system then the first word that comes to my mind is my transaction. If I refer paypal. I will see my transactions. I will see history of transactions. My perspective to the screen and its function is right now as a user or customer. So when i saw the screen I see it as transactions that i do on the platform

I saw the link you shared with me... the way they have shown personal menu is good but i dont think it is required for Orders/ Transactions.

**Comment by galenp** [comment] 2015-04-29 07:26
I respect your input and happy to continue this discussion.

Pay Pal is a payment gateway... in that domain a line item is exactly a transaction. If anything this supports my point slightly more as we will also link into PayPal and the term transaction will be used to refer specifically to that.

Current flow:
- user creates a new review
- this creates a new Order
- the product type that the user has requested is added to the Order as an OrderLineItem
- the price for that OrderLineItem is loaded up from a products catalogue (note that this price may vary depending on the type of user subscription)
- the order system could then handle applicable tax lookups
- the order system could then handle applicable currency conversions
- the order system provides an 'Amount Owing' and is considered 'Pending Approval'
- OrderApproval could come automatically (via a payment) or Manually (via business administrators)
- Typically the user would click Pay and go through the payment process... when the user triggers the Payment process the 'Amount Owing' and all the details necessary to facilitate the payment and passed from the Order into the Payments system .. as well as a valid PaymentMethod (either new or existing)
- The payments system will attempt then create a Transaction representing the success or failure of the attempted payment. If for example the credit card declined the transaction because of insufficient funds then a DeclinedTransaction event would be raised in the system.

So what i'm trying to get at is that Transactions are associated to Payments and that is why in PayPal its called transactions.

Since we have this abstract concept called an Order that could be approved without an upfront payment (in the future) we need a term to describe it. Fortunately this is not a new concept as Purchase Orders or Orders are the term used in the business world for this exact purpose.

You make a very good point in terms of a 'Transaction History' that a user could look at on the platform that represents all of the transactions they have done. This can still exist and still be called exactly Transaction history because it could be a log of all the successful or failed payments the user has made within the platform. I see value in such a list. However I do not think that this specific list in question (My Orders) is the same thing.

Galen

**Comment by galenp** [comment] 2015-04-29 07:30
Please understand i do acknowledge the usability points you are raising.

Perhaps the solution is to not have a My Orders list at all. 
Perhaps its actually redundant if we instead had a Purchase History or Transaction History

I think the problem is actually not a labelling issue but instead identifying what the correct interface and information to show the user is at each step of the process.

The core concepts of Orders / Payments / Transactions are basically well defined in the back end of the system and wont really change. 

We can however choose what the best front end experience is for the users as they do the purchase process.

**Comment by kajalshah** [comment] 2015-04-29 07:45
Sorry Galen, I was on another screen and did not read your messages. I must say that when I looked at my orders table closely I felt like is it replicate of Purchase History or Transaction History. So I think the information that needs to be displayed in the Orders listing table needs to be given a thought.

**Comment by galenp** [comment] 2015-04-29 07:48
Maybe
- Pending Orders
  *\* Contains draft orders (like shopping cart)
  *\* Contains orders that are unapproved (either by payment or whatever)
- Purchase History
  *\* Contains a log of purchases made within property compass
  *\* Includes successful and failed transactions
  *\* Note: Its possible a purchase can occur without an Order they are not dependant on each other

We have the situation where we are having to strongly consider the direction of the product long to medium term as well as dealing with the immediate usability issues we have today and find that balance.

**Comment by kajalshah** [comment] 2015-04-29 08:17
I see value in your points for Pending Orders, Purchase History.
I would like to share an observation with you... 
Consider a situation: a user who is not much aware of the product and what is going through the system.
Flicks through the menus.
First I see Orders under Reviews
Then I see Orders as separate menu like Reviews, which is having My Orders....

I think we need something like Pending Orders, Purchase History. some thing intuitive for the user which tells them what information they are going to see through that menu.

**Comment by galenp** [comment] 2015-04-29 08:21
I agree... I'll make some changes and get your feedback.

**Comment by kajalshah** [comment] 2015-04-29 08:23
thanks

**Comment by galenp** [comment] 2015-05-01 03:08
Resolved in recent found of FrontEnd commits

**Closed as completed by galenp** 2015-05-01 03:08 UTC
Labels: 1.1 Type-Bug, 2.1 Impact-High, 3.5 Status-Resolved
