### ISSUE TITLE
Layout amend #6 the invite

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#98] opened 2016-04-11 10:54 UTC
Please see attached

AA

![layout6-invite](https://cloud.githubusercontent.com/assets/7224727/14424975/81784c46-0027-11e6-9dbb-f82c7882d99f.png)

**Comment by galenp** [comment] 2016-04-12 09:36
Please reference #103 and give feedback in the context of the fields/mapping/template we have available.

**Comment by galenp** [comment] 2016-04-13 03:02
Closing as dupe of #103

**Closed as completed by galenp** 2016-04-13 03:02 UTC
Labels: 2.3 Impact-Medium, 1.4 Type-FeatureRequest
