### ISSUE TITLE
Payment details page - Credit Card number - restrict input values

### ISSUE THREAD

**Issue by kajalshah** [galenp/PROPERTYCOMPASS.ISSUES#16] opened 2015-04-29 11:48 UTC
Please refer attached image

thanks,
![paymentdetails-cardnumber-29april2015](https://cloud.githubusercontent.com/assets/6513000/7390228/6a6bb78c-ee93-11e4-89d8-b236ae103cef.png)

**Comment by galenp** [comment] 2015-05-04 03:07
dupe of galenp/propertycompass.issues#17 closing.

**Closed as completed by galenp** 2015-05-04 03:07 UTC
Labels: 1.3 Type-Suggestion, 2.2 Impact-Low, 3.5 Status-Resolved, 3.7 Status-Dupe
