### ISSUE TITLE
ipr report and Propdata and Property data screen

### ISSUE THREAD

**Issue by anthonyaoun** [galenp/PROPERTYCOMPASS.ISSUES#55] opened 2015-05-06 07:32 UTC
![fp-7-propdata](https://cloud.githubusercontent.com/assets/7224727/7489042/c6931d70-f415-11e4-9ca3-613593df2235.png)

**Comment by galenp** [comment] 2015-05-07 04:21
Dupe of #47

**Closed as completed by galenp** 2015-05-07 04:22 UTC
Labels: 1.1 Type-Bug, 2.1 Impact-High, 3.5 Status-Resolved, 3.7 Status-Dupe
