### ISSUE TITLE
Payment details page - Pay button

### ISSUE THREAD

**Issue by kajalshah** [galenp/PROPERTYCOMPASS.ISSUES#18] opened 2015-04-29 13:18 UTC
Hello,

I entered credit card details which can pass validity criteria. It worked and I saw name of card. I can then click on Pay button. 
As a user I cannot make out from the look of the button that is it disabled or enabled. I guess the function is, until user provide correct values, Pay button is not in enabled state. So I suggest to change view of button to indicate its state.
![paymentdetails-successful-29april2015](https://cloud.githubusercontent.com/assets/6513000/7391632/2e042d9e-eea0-11e4-8c7a-ef6bdf7d6836.png)

Thanks,

**Comment by galenp** [comment] 2015-05-01 04:11
This is a dupe of galenp/PROPERTYCOMPASS.ISSUES#14

And was/will be resolved in the commit that fixed that issue. Specifically the better visibility of the  disabled button and the icon appearing on valid card numbers.

**Closed as completed by galenp** 2015-05-01 04:11 UTC
Labels: 1.3 Type-Suggestion, 3.7 Status-Dupe
